# Generated by Django 2.0.5 on 2018-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
